version: '3.9'
services:
  db:
    image: mysql:8.0.33
    restart: always
    environment:
      TZ: ${TZ}
      MYSQL_USER: ${MYSQL_USR}
      MYSQL_PASSWORD: ${MYSQL_PWD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PWD}
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3306:3306
    expose:
      - 3306
    networks:
      - kitchen-network
  fooder-core:
    image: bapadua/fooder-core:latest
    restart: always
    environment:
      TZ: ${TZ}
      MYSQL_URL: ${MYSQL_URL}
      MYSQL_USER: ${MYSQL_USR}
      MYSQL_PASSWORD: ${MYSQL_PWD}
    ports:
      - 8088:8088
    command: mvn spring-boot:run
    networks:
      - kitchen-network
    depends_on:
      - db
networks:
  kitchen-network:
    driver: bridge